#!/bin/bash
#########################Joshua Barua s3610346#########################
#######################################################################

# My github username connected with student email
github_user="acancerouscake"


# Get Updates
sudo apt-get update

# Install binaries required
sudo apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make

# Repo with linux kernel to clone
git clone --depth=1 https://github.com/raspberrypi/linux

# Clone repo file with config
git clone --depth=1 https://github.com/$github_user/USAP-COSC1133-s3610346

# Copy config file to linux repo
cp ./USAP-COSC1133-s3610346/.config ./linux

# Move into linux directory
cd ./linux

# Kernel Version
KERNEL=kernel7l

# Kernel starts make process
sudo make -j4 zImage modules dtbs & sudo ../USAP-COSC1133-s3610346/vcgencmd

# Installl modules
sudo make modules_install

# Backup old boot files
sudo cp -r /boot/. /home/boot_backup

#Compress boot back up file
sudo tar -zcvf /home/boot_backup.tar.gz /home/boot_backup
sudo rm -rf /home/boot_backup

# Copy final files to required destinations
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img

sudo reboot