#!/bin/bash
######################### Joshua Barua s3610346 #########################
#######################################################################

# My github username connected with student email
github_user="acancerouscake"
myUser=$(whoami)


#Add user to video group to enable vcgencmd to avoid "VCHI initialization failed"
sudo usermod -aG video $myUser

# Run temperature log script as background process
./vcgencmd &> ./kernel_build_temp_data &

# Grab process ID of vcgencmd script
tempPID=$!

# function tto kill pid for use in trap
killFunc(){
kill -15 $tempPID
exit
}

# Event handling of USR1 signal
trap "killFunc" USR1

# Get Updates
sudo apt-get update

# Install binaries required
sudo apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make

# Repo with linux kernel to clone
git clone --depth=1 https://github.com/raspberrypi/linux

# Clone repo file with config
git clone --depth=1 https://github.com/$github_user/USAP-COSC1133-s3610346

# Copy config file to linux repo
cp ./USAP-COSC1133-s3610346/.config ./linux

# Move into linux directory
cd ./linux

# Kernel Version
KERNEL=kernel7l

# Kernel starts make process 
# Event handler for USR1 to stop gracefully after "make" has finished ***
sudo make -j4 zImage modules dtbs

# Installl modules
sudo make modules_install

# Backup old boot files
sudo cp -r /boot/. ./boot_backup

#Compress boot back up file
sudo tar -zcvf ./boot_backup.tar.gz ./boot_backup
sudo rm -rf ./boot_backup

# Copy final files to required destinations
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img

#Kill Process of vcgencmd temperature log
kill -15 $tempPID

# Reboots sytem to enable changes
sudo reboot