#!/bin/bash
#########################Joshua Barua s3610346#########################
#######################################################################

# Temperature Script for cpu during build_kernel operation
echo "Build_kernel, is running. Logging CPU temperature"

# add Seconds variable
start=$SECONDS

# printf for formatting
printf "%s\t%s\t\n" "Time" "Temperature" 
printf "%10s\n" "..................."

# While loop for logging
while true
do
# Renaming long command to "temp". egrep removes "'C"
temperature=$(vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*')

# Renaming long command to "time". "%s" adjusts time to epoch
duration=$(( SECONDS - start))
printf "%s\t%s\t\n" "$duration" "$temperature"
sleep 5
# File create for storage of temp data
touch kernel_build_temp_data 
# Log temperatures to file
echo "$temperature" >> kernel_build_temp_data 
done
